/**
 * 面试准备包渲染（痛点解决方案批次 1，求职者侧）。
 *
 * 纯函数、无 I/O：输入画像快照 + 证据明细（含外链 URL）+ 语言，输出 Markdown。
 * 内容全部来自画像已有证据，不新增任何结论；面试题附上可点击的原始证据，
 * 方便求职者围绕"自己真正做过的事"准备，而不是背通用八股。
 */
import {
  composeHeadline,
  composeSignalLabel,
  composeSignalDetail,
  composeInterviewIntent,
  headlineFactsFromProfile,
} from '@jobagent/shared';
import type { AbilityProfile, EvidenceItem, SkillTagKind } from '@jobagent/shared';
import type { Locale } from '../i18n/index.js';

type Dict = {
  title: string;
  account: string;
  generatedAt: string;
  headline: string;
  skills: string;
  language: string;
  framework: string;
  domain: string;
  depthUsed: string;
  depthProficient: string;
  authenticity: string;
  confidence: string;
  questions: string;
  intent: string;
  evidence: string;
  noEvidence: string;
  caveats: string;
  footer: string;
  quantifiedHeading: string;
  jobHeading: string;
  matchedSkillsLabel: string;
  askBackHeading: string;
  askBackTemplate: (skill: string) => string;
  noSkills: string;
  noQuantified: string;
};

const ZH: Dict = {
  title: '面试准备包',
  account: '账号',
  generatedAt: '生成时间',
  headline: '能力概述',
  skills: '能力标签',
  language: '编程语言',
  framework: '框架 / 工具',
  domain: '领域能力',
  depthUsed: '使用过',
  depthProficient: '有深度',
  authenticity: '真实性结论',
  confidence: '置信度',
  questions: '基于真实项目的面试题',
  intent: '考察意图',
  evidence: '原始证据',
  noEvidence: '（暂无可点击的原始证据）',
  caveats: '局限与说明',
  footer:
    '> 本准备包由 JobAgent 基于公开的代码托管行为痕迹生成，所有面试题均关联真实项目证据。请围绕你实际做过的内容准备，如实作答。',
  quantifiedHeading: '量化概览',
  jobHeading: '岗位定向准备',
  matchedSkillsLabel: '岗位命中技能',
  askBackHeading: '你该反问什么',
  askBackTemplate: (skill) => `针对「${skill}」：面试官最看重哪个层面的深度，是原理、工程实践还是性能调优？`,
  noSkills: '（暂无命中技能数据）',
  noQuantified: '（画像无活动量化数据）',
};

const EN: Dict = {
  title: 'Interview Prep Kit',
  account: 'Account',
  generatedAt: 'Generated at',
  headline: 'Summary',
  skills: 'Skill tags',
  language: 'Languages',
  framework: 'Frameworks / tools',
  domain: 'Domain skills',
  depthUsed: 'used',
  depthProficient: 'proficient',
  authenticity: 'Authenticity',
  confidence: 'Confidence',
  questions: 'Interview questions grounded in real projects',
  intent: 'Intent',
  evidence: 'Source evidence',
  noEvidence: '(no clickable source evidence)',
  caveats: 'Caveats',
  footer:
    '> Generated by JobAgent from public code-hosting activity. Every question links to real project evidence. Prepare around what you actually built and answer honestly.',
  quantifiedHeading: 'Quantified overview',
  jobHeading: 'Job-targeted prep',
  matchedSkillsLabel: 'Matched skills',
  askBackHeading: 'Questions to ask back',
  askBackTemplate: (skill) =>
    `For "${skill}": which depth matters most to you — principles, engineering practice, or performance tuning?`,
  noSkills: '(no matched skill data)',
  noQuantified: '(no activity metrics in profile)',
};

const KIND_HEADINGS: Record<SkillTagKind, keyof Dict> = {
  language: 'language',
  framework: 'framework',
  domain: 'domain',
};

/** 面试题只有单个 basisEvidenceRef；返回可点击的证据行，无 URL 时返回降级提示。 */
function evidenceLine(ref: string | undefined, byId: Map<string, EvidenceItem>, d: Dict): string {
  const ev = ref ? byId.get(ref) : undefined;
  if (ev && ev.url) return `    - ${d.evidence}: [${ev.claim}](${ev.url})`;
  return `    - ${d.evidence}: ${d.noEvidence}`;
}

/** 渲染面试准备包 Markdown。evidence 提供 evidenceId → 含 URL 的证据明细。 */
/** 岗位定向输入（T16）：有岗位数据时渲染"岗位定向准备 + 反问建议"区块；缺省走通用版。 */
export interface InterviewKitOptions {
  posting?: { title: string; company?: string; sourceUrl?: string };
  /** 岗位命中技能（matchJobs 的 matchedSkills，原始写法） */
  matchedSkills?: string[];
}

export function renderInterviewKit(
  profile: AbilityProfile,
  evidence: EvidenceItem[],
  locale: Locale,
  opts?: InterviewKitOptions,
): string {
  const d = locale === 'zh-CN' ? ZH : EN;
  const byId = new Map(evidence.map((e) => [e.evidenceId, e]));
  const lines: string[] = [];

  lines.push(`# ${d.title} · ${profile.subject.displayName ?? profile.subject.login}`);
  lines.push('');
  lines.push(`- ${d.account}: [@${profile.subject.login}](${profile.subject.profileUrl})`);
  lines.push(`- ${d.generatedAt}: ${profile.generatedAt}`);
  lines.push('');

  lines.push(`## ${d.headline}`);
  lines.push(composeHeadline(headlineFactsFromProfile(profile), locale));
  lines.push('');

  // 量化概览（T14）：合并 PR 数 / 活跃仓库数 / 持续月数，均来自 activity.metrics；
  // 缺任一键则整行省略（不写半句、不造数），旧快照自然兼容。
  const m = profile.activity.metrics;
  if (m && typeof m.mergedPullRequests === 'number' && typeof m.commitRepoCount === 'number' && typeof m.activeMonths === 'number') {
    lines.push(`## ${d.quantifiedHeading}`);
    lines.push(
      locale === 'zh-CN'
        ? `已合并 ${m.mergedPullRequests} 个 PR，覆盖 ${m.commitRepoCount} 个活跃仓库，持续 ${m.activeMonths} 个月。`
        : `Merged ${m.mergedPullRequests} pull request(s) across ${m.commitRepoCount} active repositories over ${m.activeMonths} months.`,
    );
    lines.push('');
  }

  // 岗位定向（T16）：岗位 + 命中技能，每条技能挂其证据行（可回溯）。
  if (opts?.posting && opts.matchedSkills?.length) {
    const job = opts.posting;
    lines.push(`## ${d.jobHeading}`);
    lines.push(
      locale === 'zh-CN'
        ? `目标岗位：**${job.title}**${job.company ? ` @ ${job.company}` : ''}${job.sourceUrl ? ` [${d.evidence}](${job.sourceUrl})` : ''}`
        : `Target role: **${job.title}**${job.company ? ` @ ${job.company}` : ''}${job.sourceUrl ? ` [${d.evidence}](${job.sourceUrl})` : ''}`,
    );
    lines.push('');
    lines.push(`### ${d.matchedSkillsLabel}`);
    const tagsBySkill = new Map(profile.skillTags.map((t) => [t.name, t]));
    for (const skillName of opts.matchedSkills) {
      const tag = tagsBySkill.get(skillName);
      if (!tag || tag.evidenceRefs.length === 0) {
        lines.push(`- **${skillName}**（${d.noEvidence}）`);
        continue;
      }
      lines.push(`- **${skillName}**`);
      for (const ref of tag.evidenceRefs) lines.push(evidenceLine(ref, byId, d));
    }
    lines.push('');
  }

  // 能力标签按 kind 分组
  lines.push(`## ${d.skills}`);
  const kinds: SkillTagKind[] = ['language', 'framework', 'domain'];
  for (const kind of kinds) {
    const tags = profile.skillTags.filter((s) => s.kind === kind);
    if (tags.length === 0) continue;
    lines.push(`### ${d[KIND_HEADINGS[kind]]}`);
    for (const tag of tags) {
      const depth = tag.depth === 'proficient' ? d.depthProficient : d.depthUsed;
      lines.push(`- **${tag.name}**（${depth}）`);
    }
    lines.push('');
  }

  // 真实性结论
  lines.push(`## ${d.authenticity}`);
  lines.push(`${d.confidence}: ${Math.round(profile.authenticity.confidence * 100)}%`);
  for (const signal of profile.authenticity.signals) {
    lines.push(
      `- ${composeSignalLabel(signal.code, locale, signal.label)}: ${composeSignalDetail(signal.code, locale, signal.detail, signal.facts)}`,
    );
  }
  lines.push('');

  // 面试题 + 证据
  lines.push(`## ${d.questions}`);
  if (profile.interviewQuestions.length === 0) {
    lines.push(d.noEvidence);
    lines.push('');
  } else {
    profile.interviewQuestions.forEach((q, i) => {
      lines.push(`${i + 1}. **${q.question}**`);
      lines.push(`    - ${d.intent}: ${composeInterviewIntent(q.kind, locale, q.intent)}`);
      lines.push(evidenceLine(q.basisEvidenceRef, byId, d));
      lines.push('');
    });
  }

  // 该反问什么（T16）：纯规则，按岗位命中技能逐条生成，不新造事实
  if (opts?.matchedSkills?.length) {
    lines.push(`## ${d.askBackHeading}`);
    opts.matchedSkills.forEach((skill, i) => {
      lines.push(`${i + 1}. ${d.askBackTemplate(skill)}`);
    });
    lines.push('');
  }

  // 局限
  if (profile.caveats.length > 0) {
    lines.push(`## ${d.caveats}`);
    for (const caveat of profile.caveats) lines.push(`- ${caveat}`);
    lines.push('');
  }

  lines.push(d.footer);
  lines.push('');
  return lines.join('\n');
}
